name = "D. Evans"
rol = "IT & AV Specialist"
LinkedIn = "https://www.linkedin.com/"
birthday = "Gemini"
location = "USA"
avatar = "https://i.imgur.com/em6jmBT.jpeg"
username = "devanssound" # <-- github user name
presentation = """
Hi! 
I have over 10 years of experience in Audiovisual and IT technologies working out of Raleigh, NC, USA. 
I enjoy tuning complex systems by designing applications and scripts to solve company workflows.
"""
